name: advent2020
version: 0.1.0.0
github: "jakeswenson/advent2020"
license: BSD3
author: "Jake Swenson"
maintainer: "jakeswenson@outlook.com"
copyright: "2020 Jake Swenson"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jakeswenson/advent2020#readme>

dependencies:
  - base >= 4.7 && < 5
  - either
  - megaparsec
  - text
  - containers

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent2020

tests:
  aoc2020-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent2020
      - hspec
      - tasty
      - tasty-hunit
